name: GH Pages on release

on:
  workflow_dispatch:
  push:
    branches: [master]
env:
  DEPENDENCIES_CACHE: cache-node-modules
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --ignore-platform
      - run: mkdir /home/runner/work/ngrid-starters/ngrid-starters/.cache
      - run: node_modules/.bin/ng build material --prod --deploy-url ngrid-starters/material/
      # - run: cp ./dist/apps/ngrid-starters/material/index.html ./dist/apps/ngrid-starters/material/404.html
      - run: node_modules/.bin/ng build bootstrap --prod --deploy-url ngrid-starters/bootstrap/
      # - run: cp ./dist/apps/ngrid-starters/bootstrap/index.html ./dist/apps/ngrid-starters/bootstrap/404.html
      - run: ls -l

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/apps/ngrid-starters
          CLEAN: true
