name: GH Pages on release

on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Yarn On ACT
        if: ${{ !env.ACT }}
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --ignore-platform
      - run: ./node_modules/.bin/nx build material --configuration=production --deploy-url="/ngrid-starters/material/"
      - run: cp dist/apps/ngrid-starters/material/index.html dist/apps/ngrid-starters/material/404.html
      - run: ./node_modules/.bin/nx build bootstrap --configuration=production --deploy-url="/ngrid-starters/bootstrap/"
      - run: cp dist/apps/ngrid-starters/bootstrap/index.html dist/apps/ngrid-starters/bootstrap/404.html

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/apps/ngrid-starters
          CLEAN: true
